# Generated by Django 5.2 on 2025-05-15 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SustitucionArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_origen', models.CharField(max_length=255)),
                ('identificador_destino', models.CharField(max_length=255)),
                ('factor_conversion', models.FloatField()),
                ('tipo_operacion', models.CharField(choices=[('DIV', 'Dividir'), ('MUL', 'Multiplicar')], max_length=10)),
                ('fecha_aplicacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
