# Generated by Django 5.2 on 2025-05-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustituciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sustitucionarticulo',
            name='nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
