# Generated by Django 5.2 on 2025-05-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_lineapedido_cantidad_stock_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineapedido',
            name='identificador',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
