# Generated by Django 5.2 on 2025-05-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_lineapedido_identificador'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fecha_procesado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
