# Generated by Django 5.2 on 2025-05-14 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_pedido_fecha_procesado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumenPedidoBusinessCentral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedidos_bc_ids', models.TextField()),
                ('proveedores', models.TextField()),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resumen_bc', to='pedidos.pedido')),
            ],
        ),
    ]
