# Generated by Django 5.2 on 2025-04-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticuloPrevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('identificacion', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('almacen', models.CharField(max_length=50)),
                ('proveedor', models.CharField(blank=True, max_length=255, null=True)),
                ('familia', models.CharField(max_length=255)),
                ('subfamilia', models.CharField(blank=True, max_length=255, null=True)),
                ('anio', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('cantidad_compra', models.FloatField(default=0)),
                ('prevision_venta', models.FloatField(default=0)),
                ('stock_seguridad', models.FloatField(default=0)),
                ('cantidad_stock_final', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Previsión Artículo',
                'verbose_name_plural': 'Previsiones Artículos',
                'unique_together': {('codigo', 'anio', 'mes', 'almacen')},
            },
        ),
    ]
