# Generated by Django 5.2 on 2025-05-12 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('previsiones', '0002_alter_articuloprevision_codigo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='articuloprevision',
            unique_together={('codigo', 'anio', 'mes', 'almacen', 'identificacion')},
        ),
    ]
