# Generated by Django 5.2 on 2025-05-20 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('previsiones', '0003_alter_articuloprevision_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articuloprevision',
            name='subfamilia',
        ),
    ]
